### ISSUE TITLE
Obsolete information in README.md

### ISSUE THREAD

**Issue by Antti-L** [GAMS-dev/TIMES_MIRO#18]
As you are using the TIMES code from the TIMES_model repo, your notes (README.md) about "_two minor modifications to the TIMES source have to be made_" are no longer valid. The current TIMES v4.4.2 should no longer have those two issues.

Therefore, I would suggest removing those notes, because the code segments you present can no longer be found in the code in the way presented, and may just cause confusion.

**Comment by FFiand** [comment]
@Antti-L Thanks for the hint. This has now been resolved.
