### ISSUE TITLE
MIRO 2.5: Update custom widget icons after updating to MIRO version 2.5

### ISSUE THREAD

**Issue by rschuchmann** [GAMS-dev/TIMES_MIRO#38]
MIRO v2.5 (expected September/October) will come with an updated icon library. This includes some changes in icon names that need to be adapted in the custom input widget. `plus-circle` needs to be renamed to `circle-plus`.

**Comment by FFiand** [comment]
> MIRO v2.5 (expected September/October) will come with an updated icon library. This includes some changes in icon names that need to be adapted in the custom input widget. `plus-circle` needs to be renamed to `circle-plus`.

Thanks for the heads up. Will you create a corresponding pull request? ;-)
